---
- apt: name=bridge-utils state=present

- name: Setup bridge br-host where "{{ lxc_host_default_if }}" connects to this bridge
  template: src=../templates/interfaces.br-host dest=/etc/network/interfaces
  register: network_bridge

- name: restart_networking
  service: name=networking state=restarted
  when: network_bridge.changed
